title: GPT-3 Playground
description: >-
  Note that this plugin costs approximate one cent for every three documents analyzed, depending on the length and complexity of the prompt and documents. Give this a full prompt that you would pass into GPT-3 and it will run it against your selected documents, one at a time. Only looks at the first page of a document currently. If you define a custom model, [use the naming conventions from this section](https://beta.openai.com/docs/models/gpt-3). The prompt refers to the user input as the "Assignment," the document's text as "Document Text", and GPT-3's generated response as the "Answer," which can be helpful when defining your prompt.
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
  # By the current search query
  - query
# Properties can just be blank if you do not need any input data
properties:
  prompt:
    title: Give a GPT-3 style prompt
    type: string
  value:
    title: Put a tag here if you'd like to save the results as a key value pair.
    type: string
  model:
    title: GPT Model you'd like to use. (Optional. Leave blank if you're not sure)
    type: string

  # the key is the name of the variable that will be returned to your code

eventOptions:
  name: site
  events:
    - hourly
    - daily
    - weekly
